"""fitness

Revision ID: 672e37542434
Revises: 4faba44952e5
Create Date: 2023-06-08 22:15:37.225810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672e37542434'
down_revision = '4faba44952e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
